alias dc="docker compose"
alias fgr="find .|grep"
alias ga="git add"
alias gc="git commit -m "
alias gco="git checkout"
alias gs="git status"
alias hgr="history|grep"
alias kc="kubectl"
alias kx="kubectx"
alias l="ls -laoh"
alias pip="uv pip"
function vm () python ${HOME}/dotfiles/vm/vm.py "$@"
