#!/bin/sh

# A hook which runs `make lint` if the target lint exists in the Makefile

if [ -f Makefile ]; then
	if grep --quiet "^lint:" Makefile; then
		make lint
		ret=$?
		if [ $ret -ne 0 ]; then
				echo "Linting failed"
				exit 1
		else
				echo "Linting passed."
				exit 0
		fi
	else
		echo "No target 'lint' found in Makefile, not running linter."
	fi
else
	echo "No Makefile found, not running linter."
fi

exit 0
